### PR TITLE
update game list minimal

### PR DESCRIPTION
**Pull request by daymickcorr**

### CODE REVIEW

**Comment by daymickcorr** [comment]
Old game list was not deleted from readme, just moved into alphabetical order.

**Comment by jesinmat** [comment]
Thank you for the contribution! That's a lot of games, have you tested all of them to see whether they work? When I worked with LinuxGSM, the installer failed to install required packages several times, that's why I added the option to run `pre_install` script. Also several games require post-install configuration such as generating a password.
Since the main goal of this project is to offer fully automatic installation and create a ready-to-run server, please make sure these gameservers can install on a clean debian-based machine and will run after installation without further configuration (or create a configuration script).

**Comment by daymickcorr** [comment]
HI, I have not tested each game I've generated the folder structures, files, from the list of games from linuxgsm, essentialy it's all the games from linuxGSM, i've seen the post and preinstall scripts. 

The servers I have tested is factorio eco and valheim and they work well.

I really like the solution but I have skipped using it several times due to the lack of games, and it took me 3-4 hours to understand how the system worked, the repository has not recieved any contributions in a year. 

Iv'e tested alternatives to try to avoid having to read on linuxgsm and inspect the turnkey image like pterodactyl and pufferpanel,

I understand that a clean solution would be best, but I think it would be better to offer broken installations, because I think it would encourage contributions, personally I would have been more inclined in fixing issues rather than adding content.

**Comment by jesinmat** [comment]
Hello, sorry for the late reply. I agree with your idea that adding more games might make this project more appealing and perhaps introduce further contributions, should a need arise. Thanks for your work, I will merge this.

**Pull request merged**
