### PR TITLE
Update dependencies for Debian 12

### PR DESCRIPTION
**Pull request by OnGle**
Updated as per suggestions in upstream issue
LinuxGSM/issues/4427

### CODE REVIEW

**Comment by jesinmat** [comment]
Is this  ECO specific or for all games? If it's just for one, you can use pre-install scripts instead.
Also note that gameserver appliance should download the newest version of this repository upon first boot, so there should be no need to create bug reports there.

**Comment by OnGle** [comment]
Oh my mistake I misread the upstream issue, the netcat change is required (as the package no longer exists and has been replaced by `netcat-openbsd` or `netcat-traditional`) the additional requirements are probably ECO specific, I'll double check though and adjust them as necessary.

**Comment by OnGle** [comment]
Right so I did some testing, `netcat-openbsd` is definitely the only required change.

To correct myself earlier, `netcat` is now a virtual package (not removed) https://packages.debian.org/bookworm/netcat
So even if other games require the `netcat` package specifically, it'll already be provided by installing `netcat-openbsd`.

That also makes this less important of an issue for turnkey, as we can install `netcat-openbsd` in the plan, which will then provide `netcat` for this. However without the change the `auto-install.sh` script won't function on debian 12 systems that don't already have either `netcat-traditional` or `netcat-openbsd` install.

**Comment by jesinmat** [comment]
Looks good, thanks!

**Pull request merged**
